%scrit file name car_mdf_filemaker
%purpose:
%This program is used to generate .car file for bonds and *.lammpstrj file of REAXC
%include bondoutdata generated by bonds_analysis program in SIB
%mode or produced by bonds_analysis_speedup program (recommend)
%include tarBOinform and tarelenummatch file generated by bondorder_deepmining program
%inclunde trjdata file generated by lammpstrj_analysis program
%version 1;2018.7.16
disp('##################################################################################################################################')
disp('Welcome!--by Qiang Liu @Institute of Nuclear Physics and Chemistry, China Academy of Engineering Physics; Email: liubinqiang@163.com');
disp('Repository adress of the Source code on github: https://github.com/dadaoqiuzhi/RMD_Digging');
disp('References: 1.Fuel 287 (2021) 119484. 2.ACS Appl. Mat. Interfaces 13(34) (2021) 41287-41302. More work is coming!')
disp('##################################################################################################################################')
fprintf('\ncar_mdf_filemaker is running, please wait...')

fileheader='!BIOSYM archive 3';
title='car_mdf_filemaker Program Generated CAR File';
date=datestr(now,31);date=strcat('!DATE',date);

fid=fopen(datanamecar,'wt');
if strcmp(PBCchoi,'ON')
    fprintf(fid,'%s\n%s\n%-64s\n%s\n%3s%10.4f%10.4f%10.4f%10.4f%10.4f%10.4f %-16s',fileheader,PBC,title,date,'PBC',PBCa,PBCb,PBCc,PBCalpha,PBCbeta,PBCgamma,spacegroupname);
else
    fprintf(fid,'%s\n%s\n%-64s\n%s',fileheader,PBC,title,date);
end
element=elementsequence;
numseq={};
for i=1:length(element)
    numseq{1,i}=i;
end

[tarBOrow,~]=size(tarBOinform);line=1;
readline=1;
while readline<=tarBOrow
    if strcmp(tarBOinform{readline,1},'#')
        fprintf(fid,'\n%s','end');
        readline=readline+1;
    else
        elementname=charnum_match(element,numseq,tarBOinform{readline,2});
        if ismember(elementname,eleswap(:,1)) 
            [~,lib]=ismember(elementname,eleswap(:,1));
            elementname=eleswap{lib,2};
        end
        atomid_conv=SysConvert(tarBOinform{readline,1},base);
        if elemax==2
            if formatout==1 || formatout==2
                if 238327>=atomnum
                    atomname=strcat(elementname,atomid_conv);
                else
                    atomname=atomid_conv;
                end
            elseif formatout==3
                if 3843>=atomnum
                    atomname=strcat(elementname,atomid_conv);
                else
                    atomname=atomid_conv;
                end
            end
        elseif elemax==1
            if formatout==1 || formatout==2
                if 14776335>=atomnum
                    atomname=strcat(elementname,atomid_conv);
                else
                    atomname=atomid_conv;
                end
            elseif formatout==3
                if 238327>=atomnum
                    atomname=strcat(elementname,atomid_conv);
                else
                    atomname=atomid_conv;
                end
            end
        end
        
        [trjrow,~]=size(trjdata);tartrjdata=[];
        for i=1:trjrow
            if trjdata(i,1)==tarBOinform{readline,1}
                tartrjdata(1,:)=trjdata(i,:);
            end
        end
        if strcmpi(BOXsize,'n')
            xcoord=tartrjdata(3);ycoord=tartrjdata(4);zcoord=tartrjdata(5);
        elseif strcmpi(BOXsize,'y')
            xcoord=boxsize(1,1)+tartrjdata(3)*PBCa;
            ycoord=boxsize(2,1)+tartrjdata(4)*PBCb;
            zcoord=boxsize(3,1)+tartrjdata(5)*PBCc;
        else
            disp('Illegal BOXsize parameters!!!')
        end

        ff=forcefield(element,numseq,tarBOinform{readline,2});
        if ismember(upper(ff),eleswap(:,1)) 
            [~,lib]=ismember(upper(ff),eleswap(:,1));
            ff=lower(eleswap{lib,2});
        end
        charge=tarBOinform{readline,15};
        fprintf(fid,'\n%-5s %14.09f %14.09f %14.09f %-12s%-7s %-2s %6.3f',atomname,xcoord,ycoord,zcoord,residueseqname,ff,elementname,charge);
        readline=readline+1;
    end
end
fprintf(fid,'\n%s\n','end');
fclose(fid);    
fprintf('\ncar_mdf_filemaker is successfully finished.')


clear ans atomname charge element elementname ff fid numseq 
clear tarrow xcoord  ycoord  zcoord topo topocol  
clear molecule comatomname connect row connectivity i j k line 
clear BOinform lineofmolecule numofmolecule tarBOrow tarmatchcol trjrow readline 