%scrit file name bondanamain
%purpose:
%This is the main program used to analyze the bonds file generated by
%reaxc package in LAMMPS.
%include functions:bonds_analysis bondorder_capture and bondorder_deepmining
%version 1;2018.6.29
disp('Welcome!--by Qiang Liu @Institute of Nuclear Physics and Chemistry, China Academy of Engineering Physics; Email: liubinqiang@163.com');
disp('Repository adress of the Source code on github: https://github.com/dadaoqiuzhi/RMD_Digging');

fprintf('\nThis program is the integration of: \n1.bonds_analysis (BO read)\n2.bonds_analysis with acceleration algorithm.')
fprintf('\n3.bondorder_capture (simple analysis)\n4.bondorder_deepmining (deep mining and classification)')
fprintf('\n5.speciesbond_classify (clustering and sorting)\n6.bondedatom_tracking (specific atom tracking)\n')

while true
    progchoi=input('Please input the analysis options(1,2,3,4,5 or 6): \n');
    switch progchoi
        case 1
            bonds_analysis
        case 2
            bonds_analysis_speedup
        case 3
            bondorder_capture
        case 4
            bondorder_deepmining
        case 5
            speciesbond_classify
        case 6
            bondedatom_tracking
        otherwise
            disp('Illegal input, please input the correct analysis options (1,2,3,4,5 or 6)')
    end
    fprintf('\nThis program is the integration of: \n1.bonds_analysis (BO read)\n2.bonds_analysis with acceleration algorithm.')
    fprintf('\n3.bondorder_capture (simple analysis)\n4.bondorder_deepmining (deep mining and classification)')
    fprintf('\n5.speciesbond_classify (clustering and sorting)\n6.bondedatom_tracking (specific atom tracking)\n')

    fprintf('\n\nTo exit: Ctrl+c\n')
    clear progchoi
end
